tap "homebrew/cask-fonts"

brew "figlet"
brew "lazygit"
brew "lolcat"
brew "neovim", args: ["HEAD"]
brew "nodenv"
brew "pyenv"
brew "ripgrep"
brew "zsh"

cask "alfred"
cask "bitwarden"
cask "docker"
cask "flux"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "obsidian"
cask "postman"
cask "rectangle"
cask "spotify"
cask "telegram"
cask "toggl-track"
cask "visual-studio-code"