tap "homebrew/cask-fonts"
brew "ripgrep"
brew "lolcat"
brew "neovim", args: ["HEAD"]
brew "nodenv"
brew "zsh"
brew "pyenv"
brew "figlet"

cask "visual-studio-code"
cask "blackhole-2ch"
cask "rectangle"
cask "obsidian"
cask "selfcontrol"
cask "bitwarden"
cask "google-chrome"
cask "alfred"
cask "docker"
cask "flux"
cask "google-backup-and-sync"
cask "iterm2"
cask "spotify"
cask "telegram"
cask "toggl-track"